### ISSUE TITLE
startATMode method does not validate handshake from Wifi module

### ISSUE THREAD

**Issue by jdcockrill** [digistump/DigiFi#10]
The initial AT mode handshake method, startATMode, does not validate than an 'a' character is returned by the Wifi module after the user initiates the command mode handshake with the '+++' characters. This is the behaviour described by the datasheet.

Failing to do this may mean that your code may think you are in configuration mode when you are not and AT commands may be printed out over the TCP connection to the recipient, causing unexpected behaviour.

**Comment by digistump** [comment]
Closed with commit 99acfdde795bacf676c387344b0658d04c877dd8 thanks again!
