### ISSUE TITLE
Comparison of Content-Length header with "0" string fails

### ISSUE THREAD

**Issue by jdcockrill** [digistump/DigiFi#13]
Comparison of the results of sub-stringing the Content-Length header with "0" string fails to work as expected. Having tested this against my own application I have found this to not validate as expected (i.e. cause the method to skip waiting to receive a body) and can cause the method to hang as the server will send no further data.

I have found that this has caused my DigiX to unexpectedly hang when making requests to applications I run hosted with lighttpd and Apache with fastcgi and mod_wsgi.

**Comment by digistump** [comment]
Am I correct in thinking this is also solved by your commits?

**Comment by digistump** [comment]
Answered by your post on the forums - thanks!
