### ISSUE TITLE
readResponse method can hang if server unexpectedly disconnects

### ISSUE THREAD

**Issue by jdcockrill** [digistump/DigiFi#14]
The readResponse method is constructed such that if you are not at the "end" (determined by the code) and the Serial connection is not available, you can hang your application within the readResponse method indefinitely.

A timeout should be added that is long enough that it is unfeasible that the DigiX would have ever wanted to retrieve so much data anyway (15 seconds, the standard timeout in the header file) is probably sufficient.

**Comment by digistump** [comment]
Closed with commit 99acfdd thanks again!
