### ISSUE TITLE
Web Server

### ISSUE THREAD

**Issue by emcniece** [digistump/DigiFi#4]
Is it possible to use this library to create a web server? The DigiX has a configuration page that can be accessed at 10.10.100.254, so it must be possible some how. There is an Arduino Web Server library available, but it uses the Ethernet shield library... can this be accomplished with DigiFi and the DigiX?

**Comment by digistump** [comment]
This should probably be implemented as separate library or branch to this library -  per my response on the forums, the module supports this, it won't replace the config page, and implementing is very simialr to the client implementation by this library.

**Comment by AlinaNova21** [comment]
You can actually put the DigiX into server mode easily with setNetParams. After that it will allow one TCP connection at a time to connect. Browser will send the headers and you simply respond with your own headers and content.
<code>
wifi.startATMode();
wifi.setNetParams("TCP","SERVER",80,"");
wifi.endATMode();
</code>

**Comment by emcniece** [comment]
Sounds easy enough. Will this override the previous configuration already existing for the Wifi setup screens when you first browse to 10.10.100.254?

**Comment by emcniece** [comment]
Right, so placing the device in server mode seems to be working - or at the very least compiling and executing without issue. How does the device then listen and interpret incoming requests?

The code I have so far is this:

```
#include <DigiFi.h>
DigiFi wifi;

void setup()
{
  Serial.begin(9600); 
  wifi.begin(9600);

  //DigiX trick - since we are on serial over USB wait for character to be entered in serial terminal
  while(!Serial.available()){
    Serial.println("Enter any key to begin");
    delay(1000);
  }

  Serial.println("Starting");

  while (wifi.ready() != 1)
  {
    Serial.println("Error connecting to network");
    delay(15000);
  }  

  Serial.println("Connected to wifi!");
  wifi.startATMode();
  wifi.setNetParams("TCP","SERVER",22,"");
  wifi.endATMode();
//  wifi.close();
}

void loop()
{
  String tempString;
  tempString = wifi.recvData(128);

  if( tempString){
     Serial.println( tempString );
  }
}
```

**Comment by digistump** [comment]
The data sent by the client (connecting party) will be available at Serial1
Send data back to Serial1 to respond - presumably with appropriate headers followed by data.

I'll work up an example/start of a library when I can but this should get it working - swap your loop out for this:

``` arduino
void loop()
{
  while( Serial1.available()){
     Serial.write( Serial1.read());
  }
}
```

**Comment by emcniece** [comment]
Awesome, thanks! No worries on the example, we're all busy... I'll just keep bugging you guys here ;). And if I can get this to work, I'll even write the example or a tutorial for you!

Next issue: no matter how I try to setNetParams, the chip won't switch away from port 80, and it never returns any results on Serial1. I suspect that there is a conflict between the built-in web config and the sketch I'm running.

Sketch:

```
#include <DigiFi.h>
DigiFi wifi;

void setup()
{
  Serial.begin(9600); 
  wifi.begin(9600);

  //DigiX trick - since we are on serial over USB wait for character to be entered in serial terminal
  while(!Serial.available()){
    Serial.println("Enter any key to begin");
    delay(1000);
  }

  Serial.println("Starting");

  while (wifi.ready() != 1)
  {
    Serial.println("Error connecting to network");
    delay(15000);
  }  

  Serial.println("Connected to wifi!");
  wifi.startATMode();
  wifi.setNetParams("TCP","SERVER",666,"");
  wifi.endATMode();
//  wifi.close();
}

void loop()
{
  Serial.println("Waiting for Serial1...");
  while( Serial1.available()){
    Serial.println("Event!");
     Serial.write( Serial1.read() );
  }
  delay(1000);

    wifi.startATMode();
    Serial.println( wifi.getNetParams() );
    wifi.endATMode();

  delay(1000);  
}
```

Altered DigiFi.cpp, starting at line 473:

```
void DigiFi::setNetParams(char *proto, char *cs, int port, char *ip)
{
    // Testing for port to make sure it gets here!
    Serial.print("Port: "); 
    Serial.println( port);

    Serial1.print("AT+NETP=");
    Serial1.print(proto);
    Serial1.print(",");
    Serial1.print(cs);
    Serial1.print(",");
    Serial1.print(port);
    Serial1.print(",");
    Serial1.print(ip);
    Serial1.print("\r");
    readResponse(0);
}
```

Serial output:

```
+ok=TCP,Server,80,192.168.0.107

Waiting for Serial1...
+ok=TCP,Server,80,192.168.0.107

Waiting for Serial1...
+ok=TCP,Server,80,192.168.0.107

Waiting for Serial1...
+ok=TCP,Server,80,192.168.0.107
```

Any thoughts?

**Comment by digistump** [comment]
The web config won't conflict - that I'm 99% sure of - I'll run this right now and see what I come up with...

**Comment by digistump** [comment]
But for the sake of testing you can try changing it in web config - it should stick when your sketch runs if you don't call setNetParams

**Comment by emcniece** [comment]
TOTALLY WORKED. I moved the web config TCP-Server Port ID to 8080, then updated the sketch to 

```
wifi.setNetParams("TCP","SERVER",8080,"");
```

... and as soon as I hit the device on 192.168.0.107:8080, Serial1 spat out a ton of request data!

**Comment by digistump** [comment]
So it should work with setNetParams (and not require the web interface change) - Its not taking the changes at all - not just the port - so if you have it set to client and then do . wifi.setNetParams("TCP","Server",80,""); it doesn't change at all - looking into why now - I think it is invalid in some way so it just throws it out.

**Comment by digistump** [comment]
Got it - wifi.setNetParams("TCP","SERVER",80,"127.0.0.1");
the 127.0.0.1 can be anything (because the server mode doesn't use it) but it can't be empty

**Comment by digistump** [comment]
and it can't be 80 or it just brings up the web interface - you were right about that - I was thinking of a conflict as far as resources/internal port assignments and somehow completely missing the point that two web servers can't be on one port

**Comment by emcniece** [comment]
Interesting! I had a feeling that might be the case, but I have no idea how the wifi stack handles information. Thanks a ton for troubleshooting. 

Of course, the next question might be something like this: How do we free up port 80 and move the web config to an alternate location?

**Comment by digistump** [comment]
That's a good question to which I don't' have an answer yet - looking at the datasheet nothing jumps out at me as allowing that to change easily (though I'm getting over the flu so I won't claim to have taken a good look). 

The firmware can be replaced completely and that would allow it, but it would be nice to have something simpler.

**Comment by emcniece** [comment]
Haha I'm recovering as well! Don't worry about it, that's lots of progress for one night. I'll take a gander as well and will poke around a bit.

**Comment by digistump** [comment]
I've got basic web server functionality added to library - pushing in a few minutes

**Comment by digistump** [comment]
Latest commit has example of new functions for basic web server - I'm going to close this issue since web server is now supported, feel free to open new specific ones related to web server features like the port 80 conflict.
